controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

homepage:
    path: /
    controller: App\Controller\DefaultController::index

restaurant.show:
    path: /restaurants/show/{slug}
    controller: App\Controller\RestaurantController::show

logout:
    path: logout
    methods: GET